# Site settings
title: Wayfare
email: hi@wayfare.io
description: "We believe in the world's best future."
url: http://wayfare.io
twitter_username: wayfarehq

# Build settings
encoding: utf-8
timezone: US/Pacific
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "README.md"]
markdown: kramdown
kramdown:
  entity_output: :symbolic
relative_permalinks: true
assets:
  dirname: public-assets
  baseurl: /public-assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard


# Post permalink style
permalink: /blog/:year/:month/:title/

# Page defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header: "header-default.html"
  -
    scope:
      path: "blog"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
